### ISSUE TITLE
Homebridge

### ISSUE THREAD

**Issue by fastenspy** [pipolaq/maestro#2]
Je vois la un très beau boulot, existe-il un moyen de faire tourner ceci sur un rPi via la plateforme Homebridge?

**Comment by pipolaq** [comment]
Hello,
De mon côté j'utilise jeedom (et homebridge expose jeedom dont les thermostats et le pôele), donc pas prévu de l'intégrer directement avec homebridge.
Peut-être une piste : https://github.com/PJCzx/homebridge-thermostat
